keys:
  # Personal key (run: nix-shell -p age --run "age-keygen -y ~/.config/sops/age/keys.txt")
  - &user_ktvsky age1p8q3qpu487gzt8wx9z8azvyg5uqy86hmchekmmrp6ty9f4pm7stqr5vuqk

  # Laptop user SSH key (run: nix-shell -p ssh-to-age --run "ssh-to-age < ~/.ssh/id_ed25519.pub")
  - &user_ktvsky_laptop age13smcr3l5j834v9end7ujgcp5j8xudnrn3rhl2t33ea6hprcq7ggqlctf9w

  # Machine keys (run on each host: nix-shell -p ssh-to-age --run "ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub")
  - &host_laptop age19k355cf8qg004e030ltaq8yqjgr0ecwgdeaau8ny20vxh8zl7umqeu200d
  - &host_desktop age1r302n5u6cux3fx0jq2mw5s9zt3q2wytuewy5wmsunc86xeds3pmsymfdhn

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_ktvsky
      - *user_ktvsky_laptop
      - *host_laptop
      - *host_desktop
