# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.kernelParams = [ "amd_pstate=active" ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  hardware.bluetooth.enable = true;
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5a26d93f-cd71-4c04-b734-9e8e929a1155";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6EAB-3ED7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # hand written
  hardware.graphics = {
    enable = true;
  };
  services.fwupd.enable = false;
  services.xserver.videoDrivers = ["nvidia" "amdgpu"];
  hardware.nvidia = {
    modesetting.enable = true;
	powerManagement.enable = false;
	powerManagement.finegrained = true;
	open = true;
	nvidiaSettings = true;
    prime = {
	  offload = { enable = true; enableOffloadCmd = true; };
	  amdgpuBusId = "PCI:0:5:0";
	  nvidiaBusId = "PCI:0:1:0";
	};
  };

  environment.sessionVariables = {
    VDPAU_DRIVER = "radeonsi";
    LIBVA_DRIVER_NAME = "radeonsi";
  };
  # turn off to use tlp
  services.power-profiles-daemon.enable = false;
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
    
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
      CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
    
      CPU_MIN_PERF_ON_AC = 0;
      CPU_MAX_PERF_ON_AC = 100;
      CPU_MIN_PERF_ON_BAT = 0;
      CPU_MAX_PERF_ON_BAT = 30;
    
      # Disable dedicated GPU when on battery
      RUNTIME_PM_ON_BAT = "auto";
  };
};
}
