{
  config,
  lib,
  pkgs,
  ...
}:
let
  # Match the color scheme filename generated by Stylix's KDE target.
  colorScheme = lib.concatStrings (
    lib.filter lib.isString (builtins.split "[^a-zA-Z]" config.lib.stylix.colors.scheme)
  );
in
{
  home.packages = with pkgs.kdePackages; [
    dolphin
    kde-cli-tools # File association editor (keditfiletype).
    qtsvg
  ];

  # KDE's automatic palette selection outside Plasma can pick Breeze Light
  # while Kvantum draws a dark background. Update only the palette setting,
  # keeping dolphinrc writable so Dolphin can save its other preferences.
  home.activation.dolphinColorScheme =
    lib.mkIf (config.stylix.enable && config.stylix.targets.kde.enable)
      (
        lib.hm.dag.entryAfter [ "linkGeneration" ] ''
          run ${pkgs.kdePackages.kconfig}/bin/kwriteconfig6 \
            --file "${config.xdg.configHome}/dolphinrc" \
            --group UiSettings --key ColorScheme ${lib.escapeShellArg colorScheme}
        ''
      );

  dconf.settings = {
    # GTK file chooser dialogs (open/save)
    "org/gtk/gtk4/settings/file-chooser" = {
      show-hidden = true;
    };
    "org/gtk/settings/file-chooser" = {
      show-hidden = true;
    };
  };
}
