{
  config,
  osConfig,
  pkgs,
  lib,
  ...
}:

let
  # An absolute checkout path, not a Nix path copied into the read-only store.
  sharedMimeApps = config.lib.file.mkOutOfStoreSymlink (
    "${config.home.homeDirectory}/.dotfiles/nixos/home/modules/xdg/mimeapps.list"
  );

  nvimPkg =
    if (osConfig.programs.nixvim.package or null) != null then
      osConfig.programs.nixvim.package
    else if (osConfig.programs.nixvim.finalPackage or null) != null then
      osConfig.programs.nixvim.finalPackage
    else
      pkgs.neovim;

  nvimExe = lib.getExe nvimPkg;

  terminalCmd = config.home.sessionVariables.TERMINAL or (lib.getExe pkgs.wezterm);

  # Match the color scheme filename generated by Stylix's KDE target.
  colorScheme = lib.concatStrings (
    lib.filter lib.isString (builtins.split "[^a-zA-Z]" config.lib.stylix.colors.scheme)
  );
in
{
  # Keep system fallbacks in modules/graphic/file-associations.nix, while GUI
  # choices write to the checkout and travel with it between hosts.
  xdg.mimeApps.enable = false;
  xdg.configFile."mimeapps.list".source = sharedMimeApps;
  xdg.dataFile."applications/mimeapps.list".source = sharedMimeApps;

  home.packages = [ pkgs.kdePackages.kate ];

  # Kate can choose Breeze Light for its editor outside Plasma even when the
  # rest of the Qt interface uses a dark Kvantum theme. Keep katerc writable
  # and update only the theme keys so other Kate preferences are preserved.
  home.activation.kateColorScheme =
    lib.mkIf (config.stylix.enable && config.stylix.targets.kde.enable)
      (
        lib.hm.dag.entryAfter [ "linkGeneration" ] ''
          run ${pkgs.kdePackages.kconfig}/bin/kwriteconfig6 \
            --file "${config.xdg.configHome}/katerc" \
            --group UiSettings --key ColorScheme ${lib.escapeShellArg colorScheme}
          run ${pkgs.kdePackages.kconfig}/bin/kwriteconfig6 \
            --file "${config.xdg.configHome}/katerc" \
            --group "KTextEditor Renderer" --key "Auto Color Theme Selection" false
          run ${pkgs.kdePackages.kconfig}/bin/kwriteconfig6 \
            --file "${config.xdg.configHome}/katerc" \
            --group "KTextEditor Renderer" --key "Color Theme" "Breeze Dark"
        ''
      );

  xdg.desktopEntries = lib.mkIf osConfig.programs.nixvim.enable {
    nvim = {
      name = "Neovim";
      genericName = "Text Editor";
      icon = "nvim";
      categories = [
        "Utility"
        "TextEditor"
      ];
      terminal = false;

      exec = "${lib.escapeShellArg terminalCmd} -e ${lib.escapeShellArg nvimExe} %F";

      mimeType = [
        "text/plain"
        "text/markdown"
        "application/json"
        "application/x-yaml"
        "application/x-shellscript"
      ];
    };
  };
}
